# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63907295de555531734b4cfa7a99336386966f1563aa9009d3375b3922aa3bba69aa86be2709372ca8df8aef359d65535855198dc84aa04b40388fe146ea92fa

test:
  secret_key_base: 08e74874bd861bc75c4f1b9b6b9d1589f5c37bcea9deebe88f619849e72861805185bfb821ac8c8ccee60acd94559d1d90df03b8a3cba14e7df17e073c31c9c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
